my_string = input('Кем вы работаете? ')
print(len(my_string))
print('Я тоже работаю ', my_string)
print("СТОРОКА В НИЖНЕМ РЕГИСТРЕ".lower())
print("сторока в нижнем регистре".upper())
print('Кем вы работаете? '.replace(' ',''))
print(my_string[0])
print(my_string[-1])